// cocoLabels.ts
export const COCO_LABELS = [







  // 'background',        // (Optional) 0, often background in some models
  'person',
  'bicycle',
  'car',
  'motorcycle',
  'airplane',
  'bus',
  'train',
  'truck',
  'boat',
  'traffic light',
  'fire hydrant',
  "12",
  'stop sign',
  'parking meter',
  'bench',
  'bird',
  'cat',
  'dog',
  'horse',
  'sheep',
  'cow',
  'elephant',
  'bear',
  'zebra',
  'giraffe',
  "26",
  'backpack',
  'umbrella',
  "23",
  "30",
  'handbag',
  'tie',
  'suitcase',
  'frisbee',
  'skis',
  'snowboard',
  'sports ball',
  'kite',
  'baseball bat',
  'baseball glove',
  'skateboard',
  'surfboard',
  'tennis racket',
  'bottle',
  "45",
  'wine glass',
  'cup',
  'fork',
  'knife',
  'spoon',
  'bowl',
  'banana',
  'apple',
  'sandwich',
  'orange',
  'broccoli',
  'carrot',
  'hot dog',
  'pizza',
  'donut',
  'cake',
  'chair',
  'couch',
  'potted plant',
  'bed',
  "63",
  'dining table',
  "68",
  "69",
  'toilet',
  "71",
  'tv',
  'laptop',
  'mouse',
  'remote',
  'keyboard',
  'cell phone',
  'microwave',
  'oven',
  'toaster',
  'sink',
  'refrigerator',
  "83",
  'book',
  'clock',
  'vase',
  'scissors',
  'teddy bear',
  'hair drier',
  'toothbrush',
]



// export const COCO_LABELS = [
//   "???", "person", "bicycle", "car", "motorcycle", "airplane", "bus",
//   "train", "truck", "boat", "traffic_light", "fire_hydrant", "???",
//   "stop_sign", "parking_meter", "bench", "bird", "cat", "dog", "horse",
//   "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "???", "backpack",
//   "umbrella", "???", "???", "handbag", "tie", "suitcase", "frisbee", "skis",
//   "snowboard", "sports_ball", "kite", "baseball_bat", "baseball_glove",
//   "skateboard", "surfboard", "tennis_racket", "bottle", "???", "wine_glass",
//   "cup", "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich",
//   "orange", "broccoli", "carrot", "hot_dog", "pizza", "donut", "cake",
//   "chair", "couch", "potted_plant", "bed", "???", "dining_table", "???",
//   "???", "toilet", "???", "tv", "laptop", "mouse", "remote", "keyboard",
//   "cell_phone", "microwave", "oven", "toaster", "sink", "refrigerator",
//   "???", "book", "clock", "vase", "scissors", "teddy_bear", "hair_drier",
//   "toothbrush"
// ]


export const COCO_COLORS = [
  '#ffffff','#ff0000','#ffff00','#00ffff','#808080','#008000','#adff2f','#a52a2a','#bc8f8f','#ffa500',
  '#8a2be2','#7cfc00','#000000','#228b22','#ffff00','#ffb6c1','#0000ff','#90ee90','#483d8b','#6495ed',
  '#00ffff','#00ffff','#00ffff','#00ffff','#ffff00','#e9967a','#00ffff','#ffe4c4','#00ffff','#00ffff',
  '#d2691e','#ff7f50','#fff8dc','#f5fff5','#a0522d','#00ced1','#00ffff','#dc143c','#7fff00',
  '#5f9ea0','#d2b48c','#a52a2a','#deb887','#c71585','#00ffff','#00ffff','#00ffff','#00ffff','#00ffff',
  '#f5deb3','#f0e68c','#ff6347','#40e0d0','#cd853f','#ffdab9','#ffefd5','#afeeee','#9400d3','#ffe4c4',
  '#daa520','#ff69b4','#f0fff0','#db7093','#cd5c5c','#00ffff','#8a2be2','#ff8c00','#ff4500','#f5f5f5',
  '#ffffe0','#00ffff','#00ffff','#00ffff','#778899','#008080','#d8bfd8','#da70d6','#fdf5e6','#808000','#00ffff',
] as const

// colormap.js  – label → color lookup for 80‑class COCO models
// Each entry is [label, cssColor].  Use it as:
//
//   import { COCO_COLORMAP } from './colormap';
//   const color = COCO_COLORMAP[classId][1];

export const COCO_COLORMAP = [
  ['person',          'white'],
  ['bicycle',         'red'],
  ['car',             'yellow'],
  ['motorcycle',      'aqua'],
  ['airplane',        'gray'],
  ['bus',             'green'],
  ['train',           'greenyellow'],
  ['truck',           'brown'],
  ['boat',            'rosybrown'],
  ['traffic light',   'orange'],
  ['fire hydrant',    'blueviolet'],
  ['stop sign',       'lawngreen'],
  ['parking meter',   'black'],
  ['bench',           'forestgreen'],
  ['bird',            'yellow'],
  ['cat',             'lightpink'],
  ['dog',             'blue'],
  ['horse',           'lightgreen'],
  ['sheep',           'darkslateblue'],
  ['cow',             'cornflowerblue'],
  ['elephant',        'aqua'],
  ['bear',            'aqua'],
  ['zebra',           'aqua'],
  ['giraffe',         'aqua'],
  ['backpack',        'yellow'],
  ['umbrella',        'darksalmon'],
  ['handbag',         'aqua'],
  ['tie',             'bisque'],
  ['suitcase',        'aqua'],
  ['frisbee',         'aqua'],
  ['skis',            'chocolate'],
  ['snowboard',       'coral'],
  ['sports ball',     'cornsilk'],
  ['kite',            'mintcream'],
  ['baseball bat',    'lightcoral'],
  ['baseball glove',  'darkcyan'],
  ['skateboard',      'cyan'],
  ['surfboard',       'crimson'],
  ['tennis racket',   'chartreuse'],
  ['bottle',          'cadetblue'],
  ['wine glass',      'tan'],
  ['cup',             'brown'],
  ['fork',            'burlywood'],
  ['knife',           'mediumvioletred'],
  ['spoon',           'aqua'],
  ['bowl',            'aqua'],
  ['banana',          'aqua'],
  ['apple',           'aqua'],
  ['sandwich',        'wheat'],
  ['orange',          'khaki'],
  ['broccoli',        'tomato'],
  ['carrot',          'turquoise'],
  ['hot dog',         'peru'],
  ['pizza',           'peachpuff'],
  ['donut',           'papayawhip'],
  ['cake',            'lightcoral'],
  ['chair',           'aquamarine'],
  ['couch',           'darkviolet'],
  ['potted plant',    'bisque'],
  ['bed',             'goldenrod'],
  ['dining table',    'hotpink'],
  ['toilet',          'honeydew'],
  ['tv',              'palevioletred'],
  ['laptop',          'indianred'],
  ['mouse',           'aqua'],
  ['remote',          'blueviolet'],
  ['keyboard',        'darkorange'],
  ['cell phone',      'orangered'],
  ['microwave',       'whitesmoke'],
  ['oven',            'lightyellow'],
  ['toaster',         'aqua'],
  ['sink',            'aqua'],
  ['refrigerator',    'aqua'],
  ['book',            'lightslategray'],
  ['clock',           'teal'],
  ['vase',            'thistle'],
  ['scissors',        'orchid'],
  ['teddy bear',      'oldlace'],
  ['hair drier',      'olive'],
  ['toothbrush',      'aqua'],
];
